spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
#  session:
#    store-type: redis
logging:
  level:
    org:
      apache:
        coyote:
          http11: debug
file:
  dir: /Users/sehyun/study/file/

#swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
#  paths-to-match:
#    - /**

