spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://i9a801.p.ssafy.io:3306/test
    username: ssafy
    password: jinajjang1128!
  jpa:
    hibernate:
      ddl-auto: none
  #    open-in-view: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
#server:
#  error:
#    whitelabel:
#      enabled: false

file:
  dir:
    local: /goodbe/S09P12A801/2_src/back-end/files

server:
  ip:
    local: http://localhost
    remote: 172.26.3.26
  port: 8081
#  session:
#    store-type: redis
#logging:
#  level:
#    org:
#      apache:
#        coyote:
#          http11: debug
#

#swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
#  paths-to-match:
#    - /**

